title: AengChoon
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

aux_links:
  Github: https://github.com/AengChoon

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024-2024 AengChoon."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
